apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: stage-
nameSuffix: "-001"

commonLabels:
  project: instavote
  env: stage

commonAnnotations:
  supported-by: "sre@example.com"

namespace: stage
