apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
commonLabels:
  project: instavote
  env: stage
commonAnnotations:
  supported-by: "sre@example.com"
patchesStrategicMerge:
- deployment.yaml
- service.yaml
namespace: stage
images:
- name: schoolofdevops/vote
  newTag: master-fc926e53-1619152739 # {"$imagepolicy": "flux-system:vote:tag"}
replicas:
- name: vote
  count: 3
configMapGenerator:
- name: vote
  literals:
  - OPTION_A=FluxCD
  - OPTION_B=ArgoCD
generatorOptions:
  disableNameSuffixHash: false
  labels:
    type: config
