apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonLabels:
  project: instavote
  env: stage

commonAnnotations:
  supported-by: "sre@example.com"

patchesStrategicMerge:
- deployment.yaml
- service.yaml

namespace: stage

images:
  - name: schoolofdevops/vote
    newTag: v4

replicas:
  - name: vote
    count: 4

configMapGenerator:
  - name: vote
    literals:
      - OPTION_A=STAGING
      - OPTION_B=DEV

generatorOptions:
  disableNameSuffixHash: false
  labels:
    type: config

vars:
  - name: REDIS_SERVICE
    objref:
      kind: Service
      name: vote
      apiVersion: v1
