apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vote
  name: vote
spec:
  $setElementOrder/ports:
  - port: 80
  ports:
  - name: "80"
    port: 80
    nodePort: 30100

